name: Deploy to Vercel Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Trigger Vercel Deployment
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK"
      
      - name: Deployment triggered
        run: |
          echo "✅ Vercel production deployment triggered successfully"
          echo "View deployment at: https://vercel.com/steves-projects-407285ba/gday-test-device-tracker"

